version: "3"

networks:
  vulnerable:
    name: 'vulnerable'
    driver: bridge

services:
  attacker: &attacker-base
    command: bash
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parrot
    volumes:
      - ./shm:/dev/shm
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    environment:
      - DISPLAY={$DISPLAY}
    tty: true
    stdin_open: true
    privileged: true
  
  local-attacker:
    <<: *attacker-base
    networks:
      - vulnerable
    depends_on:
      - webgoat
      - juiceshop
      - ctf

  webgoat:
    image: webgoat/goatandwolf:latest
    container_name: webgoat
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - vulnerable
    ports:
      - 8080:8080
      - 9090:9090
      - 80:8888
  
  juiceshop:
    image: bkimminich/juice-shop:latest
    container_name: juiceshop
    networks:
      - vulnerable
    ports:
      - 3000:3000

  ctf:
    image: hightechsec/web-ctf-container
    container_name: ctf
    networks:
      - vulnerable
    ports:
      - 7000:80